# action.yml
name: 'Code Review with ChatGPT'
description: 'Automating code review using ChatGPT with Github Actions integration on PRs for code explanations.'
inputs:
  openai_api_key:  # id of input
    description: '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'
    required: true
    default: ''
  github_token:  # id of input
    description: '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'
    required: true
    default: ''
  github_pr_id:  # id of input
    description: '18436751'
    required: true
    default: ''
  openai_engine:  # id of input
    description: 'GPT-3 models can understand and generate natural language. We offer four main models with different levels of power suitable for different tasks. Davinci is the most capable model, and Ada is the fastest.'
    required: false
    default: 'text-davinci-002'
  openai_temperature:  # id of input
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.'
    required: false
    default: '0.5'
  openai_max_tokens:  # id of input
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '2048'
  mode:  # id of input
    description: 'How to capture PR changes. Options: files, patch'
    required: false
    default: 'files'
runs:
  using: 'bash'
  image: 'entrypoint.sh'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
    - ${{ inputs.openai_engine }}
    - ${{ inputs.openai_temperature }}
    - ${{ inputs.openai_max_tokens }}
    - ${{ inputs.mode }}
